"""Create a .html file from the .json file."""
import json
from pathlib import Path
import pandas as pd

data_dir = Path('Open-Source_Efforts')

with open(data_dir/'WGFAST_open-source_efforts.json', 'r', encoding='utf-8') as file:
    efforts = json.load(file)

df = pd.json_normalize(data=efforts['efforts']).drop(['contact.institution'], axis=1)
df.rename(columns={'title': 'Title', 'programming_language': 'Language',
                   'description': 'Description', 'url': 'URL', 'contact.name': 'Contact name',
                   'contact.e-mail': 'Contact e-mail'}, inplace=True)
df = df[df.Title != '']  # remove blank rows

with open(data_dir/'wgfast_efforts.md', 'w', encoding='utf-8') as f:
    f.write('<!---Do not edit this file - edit the .json file and commit to the repo --->\n')
    f.write('# ' + efforts['title'] + '\n\n')
    f.write('Updated on ' + pd.Timestamp.today().strftime('%d %B %Y') + '\n\n')
    f.write(efforts['description'] + '\n\n')
    f.write(df.to_markdown(index=False, tablefmt="github"))
