= The SONAR-netCDF4 convention for sonar data

This directory contains the text, source files, and utilities that are necessary to generate the SONAR-netCDF4 convention document. It is also the place where new versions of the convention are discussed and developed.

Version 1.0 of the SONAR-netCDF4 convention (as ICES CRR No. 341) is available http://www.ices.dk/sites/pub/Publication%20Reports/Cooperative%20Research%20Report%20(CRR)/CRR341/CRR341.pdf[here].

== Getting Started

== Contributing

=== Viewing the compiled document

* *Live Preview*: Use the Asciidoctor.js Live Preview extension for Chrome, Firefox, or Opera to view asciidoc files, either from a URL or from a local file. The bibliography is not currently rendered.

* *HTML files*: After installing asciidoctor locally, use:

 asciidoctor -r asciidoctor-bibtex crr341.adoc

* *HTML (single file)*: For a single html file (including the figures, which makes it easier to distribute):

 asciidoctor -r asciidoctor-bibtex --backend html5 -a data-uri crr341.adoc
 
* *PDF*: For a PDF file (note: install the asciidoctor-mathematical extension to get the equations):

 asciidoctor-pdf -r asciidoctor-bibtex  crr341.adoc
 
* *Word (.docx)*: First convert to docbook format, then use pandoc to convert to Word:

 asciidoctor -r asciidoctor-bibtex --backend docbook crr341.adoc
 pandoc --from docbook --to docx -o crr341.docx crr341.xml
 
== Versioning

== Authors

== License

== Acknowledgements


